name: E2E Cypress Integration
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v4
      # before running the tests, start the Django server then change the working directory to the frontend
      with:
        start: python manage.py runserver
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 60
        working-directory: ./cypress
        record: true
        config-file: cypress.json
        browser: chrome
        headless: true
        spec: cypress/integration/**/*.spec.js
        env: CYPRESS_baseUrl=http://localhost:8000