name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2
      with:
        start: python manage.py runserver
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 60
        browser: chrome
        headless: true
        spec: cypress/integration/tests/*
        env: BASE_URL=http://localhost:8000
    
