name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # scripts
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Project Django
      run: |
        python manage.py runserver &
    - name: Run Cypress
      # go to the cypress folder
      working-directory: ./cypress
      run: |
        yarn add
        yarn run cypress run
