name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate --run-syncdb
      uses: actions/checkout@v2
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v4
      
      # run the tests in the "cypress" of local host app  and folder with yarn and record the results
      with:
        start: python manage.py runserver
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 60
        record: true
        config-file: cypress.json
        browser: chrome
        headless: true
        spec: cypress/integration/tests/*
        env: CYPRESS_baseUrl=http://localhost:8000
        