name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Initialize Envirement
      run: |
        python manage.py runserver
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Cypress.io
      uses: cypress-io/github-action@v4.2.0
      with:
        start: yarn run cypress run
