name: Start Django Server
on: [push]
jobs:
  start-django-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start Django Server
      uses: cypress-io/github-action@v4
      with:
        start: python manage.py runserver
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 60
        record: true
        config-file: cypress.json
        browser: chrome
        headless: true
        spec: cypress/integration/**/*.spec.js
        env: CYPRESS_baseUrl=http://localhost:8000